feat: working

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -11,14 +11,22 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+ext="tar.gz"
+if uname -a | grep -i darwin >& /dev/null; then
+	ext="zip"
+fi
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.zip"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-#tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=0 avalanchego || fail "Could not extract $release_file"
+if [[ "$ext" == "zip" ]]; then
+	unzip -od "$ASDF_DOWNLOAD_PATH" "$release_file"
+	mv "$ASDF_DOWNLOAD_PATH/build/avalanchego" "$ASDF_DOWNLOAD_PATH"
+	rm -rf "$ASDF_DOWNLOAD_PATH/build"
+else
+	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=0 avalanchego || fail "Could not extract $release_file"
+fi
 
 # Remove the tar.gz file since we don't need to keep it
-rm -rf "$release_file"
+#rm -rf "$release_file"
